### ISSUE TITLE
Locales Files + Not Updated Open Source

### ISSUE THREAD

**Issue by nooksmr** [DTanJP/Spigot-ForgetfulTrialVault#5]
Hello @DTanJP, since I can't reopen #4 and since it's still for me an issue :

> I implemented a locale file system.

I don't see such files in this repo. I also don't see any updated source code here so I can find where to check. it's like a shame, impossible to know where it comes from or even to help those who know how to develop...
I highly recommand putting open source updates and build files so we can test.

Since no updated code and only binaries are updated I can't do any PR nor see what I did wrong.
Creating and modifying config.yml for french locale file (french.yml) then restarted did nothing.

Actually only workaround might be replacing spanish or english lang files.
It should detect french files.

french.yml file :
```yml
GENERATION_MSG:
 "CONFIG_FILE": "Génération du fichier de configuration..."
 "SAVE_FILE": "Génération du fichier de sauvegarde..."
 "SAVE_FILE_ERROR": "Erreur: Unable to create save file."
 "LOADED": "CHARGÉ"
 "TRIAL_VAULTS": "Coffre-forts d'épreuves"
 
VAULT_MSG:
 "RESET": "Le coffre-fort d'épreuve a été réinitialisé."
 "TIME_LEFT1": "Vous devez attendre "
 "TIME_LEFT2": " pour réinitialiser le coffre-fort d'épreuve."
 "BUSY": "Merci de bien vouloir patienter, le coffre-fort d'épreuve éjecte des récompenses."

TIME_UNIT:
 "DAY": "Jour"
 "HOUR": "Heure"
 "MINUTE": "Minute"
 "SECOND": "Seconde"
 "MILLISECOND": "Milliseconde"
 
ERROR_MSG:
 "INVALID_BLOCK": "Ce bloc n'est pas un coffre-fort d'épreuve, aucun UUID à retirer."

PLUGIN:
 "SAVE_CONFIG": "Sauvegarde du fichier de configuration..."
 "LOAD_SAVE": "Chargement du fichier de sauvegarde..."
 "NEW_SAVE": "Fichier de sauvegarde non trouvé, génération d'un nouveau fichier de sauvegarde."
 "SAVE_ERROR": "Impossible de générer le fichier de sauvegarde!"
 "SAVE_INSTANCES": "Sauvegarde des instances de coffre-fort d'épreuve..."
 "SAVE-INSTANCE_COUNT1": "Sauvegarde des "
 "SAVE-INSTANCE_COUNT2": " coffre-forts d'épreuve."
 "INVALID_WORLD": "Coffre-fort d'épreuve invalide - monde null"
 "LOAD_INVALID_VAULT": " n'est pas un bloc coffre-fort d'épreuve valide."

COMMAND:
 "INSUFFICIENT_PRIVILEGE": "Vous devez être opérateur pour éxécuter la commande."
 "HELP-RESET": "Définir le délai de réinitialisation en milisecondes des coffre-forts d'épreuve (0 pour ne définir aucun délai)"
 "HELP-TIMER": "Activer ou désactiver l'annonce du cooldown."
 "RESET": "Temps restant avant réouverture : "
 "DISABLED": "désactivé"
 "INVALID_DELAY": "Délai défini invalide."
 "USAGE": "UTILISATION :"
 "REMAINING_TIMER": "Annonce du cooldown : "
```
